# Generated by Django 3.1.6 on 2021-02-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity_Periods',
            new_name='Activity_Period',
        ),
    ]
