# Generated by Django 3.1.6 on 2021-02-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendTest', '0002_auto_20210211_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_period',
            old_name='user_id',
            new_name='user',
        ),
    ]
